Welcome to day 1 of the 5-Day Data Challenge! Today, we're going to be looking at how to deal with missing values. To get started, click the blue "Fork Notebook" button in the upper, right hand corner. This will create a private copy of this notebook that you can edit and play with. Once you're finished with the exercises, you can choose to make your notebook public to share with others. :)

> **Your turn!** As we work through this notebook, you'll see some notebook cells (a block of either code or text) that has "Your Turn!" written in it. These are exercises for you to do to help cement your understanding of the concepts we're talking about. Once you've written the code to answer a specific question, you can run the code by clicking inside the cell (box with code in it) with the code you want to run and then hit CTRL + ENTER (CMD + ENTER on a Mac). You can also click in a cell and then click on the right "play" arrow to the left of the code. If you want to run all the code in your notebook, you can use the double, "fast forward" arrows at the bottom of the notebook editor.

Here's what we're going to do today:

* [Take a first look at the data](#Take-a-first-look-at-the-data)
* [See how many missing data points we have](#See-how-many-missing-data-points-we-have)
* [Figure out why the data is missing](#Figure-out-why-the-data-is-missing)
* [Drop missing values](#Drop-missing-values)
* [Filling in missing values](#Filling-in-missing-values)

Let's get started!

# Take a first look at the data
________

The first thing we'll need to do is load in the libraries and datasets we'll be using. For today, I'll be using a dataset of events that occured in American Football games for demonstration, and you'll be using a dataset of building permits issued in San Francisco.

> **Important!** Make sure you run this cell yourself or the rest of your code won't work!

In [2]:
# modules we'll use
import pandas as pd
import numpy as np

# read in all our data
nfl_data = pd.read_csv("../input/nflplaybyplay2009to2016/NFL Play by Play 2009-2017 (v4).csv")
sf_permits = pd.read_csv("../input/building-permit-applications-data/Building_Permits.csv")

# set seed for reproducibility
np.random.seed(0)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

The first thing I do when I get a new dataset is take a look at some of it. This lets me see that it all read in correctly and get an idea of what's going on with the data. In this case, I'm looking to see if I see any missing values, which will be reprsented with `NaN` or `None`.

In [3]:
# look at a few rows of the nfl_data file. I can see a handful of missing data already!
nfl_data.sample(5)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
244485,2014-10-26,2014102607,18,3,1.0,00:39,1,939.0,12.0,TB,...,1.240299,0.225647,0.774353,0.245582,0.754418,0.225647,0.019935,-0.018156,0.038091,2014
115340,2011-11-20,2011112000,22,4,1.0,06:47,7,407.0,44.0,OAK,...,NaN,0.056036,0.943964,0.042963,0.957037,0.943964,0.013073,NaN,NaN,2011
68357,2010-11-14,2010111401,8,2,NaN,00:23,1,1823.0,0.0,CLE,...,NaN,0.365307,0.634693,0.384697,0.615303,0.634693,-0.019390,NaN,NaN,2010
368377,2017-09-24,2017092405,24,4,1.0,08:48,9,528.0,8.0,CLE,...,1.075660,0.935995,0.064005,0.921231,0.078769,0.064005,0.014764,0.003866,0.010899,2017
384684,2017-11-05,2017110505,11,2,1.0,09:15,10,2355.0,0.0,DEN,...,NaN,0.928474,0.071526,0.934641,0.065359,0.071526,-0.006166,NaN,NaN,2017

Yep, it looks like there's some missing values. What about in the sf_permits dataset?

In [6]:
# your turn! Look at a couple of rows from the sf_permits dataset. Do you notice any missing data?
# your code goes here :)
nfl_data.sample()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
142828,2012-09-24,2012092400,3,1,1.0,09:25,10,3265.0,39.0,SEA,...,1.379042,0.522390,0.477610,0.562151,0.437849,0.522390,0.039762,-0.002897,0.042659,2012
69534,2010-11-14,2010111408,15,3,2.0,05:37,6,1237.0,46.0,NYG,...,NaN,0.053894,0.946106,0.085723,0.914277,0.053894,0.031830,NaN,NaN,2010
372672,2017-10-01,2017100111,1,1,2.0,14:23,15,3563.0,37.0,NYG,...,NaN,0.524307,0.475693,0.578703,0.421297,0.475693,-0.054396,NaN,NaN,2017
290484,2015-11-01,2015110107,18,3,NaN,15:00,15,1800.0,0.0,SF,...,NaN,0.893864,0.106136,0.889745,0.110255,0.893864,-0.004119,NaN,NaN,2015
206636,2013-11-17,2013111707,15,2,4.0,00:07,1,1807.0,5.0,PIT,...,NaN,0.260880,0.739120,0.279439,0.720561,0.739120,-0.018559,NaN,NaN,2013
399295,2017-12-14,2017121400,6,2,3.0,07:17,8,2237.0,41.0,DEN,...,NaN,0.808998,0.191002,0.786334,0.213666,0.808998,-0.022663,NaN,NaN,2017
181400,2013-09-08,2013090803,22,4,2.0,06:44,7,404.0,0.0,CLE,...,0.248509,0.118991,0.881009,0.103870,0.896130,0.118991,-0.015121,-0.015604,0.000484,2013
182573,2013-09-09,2013090901,7,2,1.0,10:09,11,2409.0,45.0,SD,...,NaN,0.622705,0.377295,0.621185,0.378815,0.377295,0.001520,NaN,NaN,2013
259043,2014-11-30,2014113011,13,3,1.0,07:23,8,1343.0,6.0,KC,...,-4.265326,0.155025,0.844975,0.098740,0.901260,0.155025,-0.056285,0.001324,-0.057609,2014
301401,2015-11-29,2015112906,4,1,3.0,04:07,5,2947.0,4.0,SD,...,NaN,0.725765,0.274235,0.768200,0.231800,0.274235,-0.042435,NaN,NaN,2015
309393,2015-12-20,2015122003,4,1,1.0,06:42,7,3102.0,37.0,JAC,...,NaN,0.315913,0.684087,0.301735,0.698265,0.315913,-0.014178,NaN,NaN,2015
61776,2010-10-24,2010102407,5,2,1.0,14:47,15,2687.0,0.0,TB,...,-0.950021,0.502178,0.497822,0.481308,0.518692,0.502178,-0.020869,0.007641,-0.028511,2010
165066,2012-11-25,2012112508,21,4,2.0,02:12,3,132.0,6.0,BAL,...,-2.820509,0.631853,0.368147,0.682449,0.317551,0.368147,-0.050597,0.179282,-0.229879,2012
70909,2010-11-21,2010112105,11,3,2.0,14:48,15,1788.0,4.0,DAL,...,0.295061,0.379192,0.620808,0.344301,0.655699,0.379192,-0.034890,-0.043868,0.008978,2010
48062,2010-09-19,2010091906,2,1,1.0,08:54,9,3234.0,41.0,PHI,...,NaN,0.441405,0.558595,0.407071,0.592929,0.558595,0.034334,NaN,NaN,2010
382447,2017-10-29,2017102903,16,4,1.0,09:36,10,576.0,9.0,LAC,...,NaN,0.736064,0.263936,0.657307,0.342693,0.263936,0.078757,NaN,NaN,2017
112534,2011-11-13,2011111300,16,4,1.0,15:00,15,900.0,0.0,BUF,...,-0.794093,0.995271,0.004729,0.996563,0.003437,0.004729,-0.001292,0.000146,-0.001437,2011
55602,2010-10-10,2010101001,18,4,NaN,14:21,15,861.0,0.0,BAL,...,NaN,0.942801,0.057199,0.942801,0.057199,0.057199,0.000000,NaN,NaN,2010
243203,2014-10-19,2014101909,6,1,1.0,00:28,1,2728.0,45.0,SD,...,NaN,0.620197,0.379803,0.626860,0.373140,0.379803,-0.006662,NaN,NaN,2014
327835,2016-10-02,2016100212,19,4,3.0,14:15,15,855.0,45.0,PIT,...,0.150238,0.999982,0.000018,0.999973,0.000027,0.999982,-0.000008,-0.000012,0.000004,2016
163432,2012-11-22,2012112202,10,2,4.0,05:08,6,2108.0,27.0,NYJ,...,NaN,0.102903,0.897097,0.099654,0.900346,0.102903,-0.003249,NaN,NaN,2012
274930,2015-09-20,2015092003,4,1,1.0,07:11,8,3131.0,19.0,TEN,...,0.809869,0.823933,0.176067,0.834691,0.165309,0.823933,0.010758,-0.006407,0.017165,2015
202785,2013-11-03,2013110307,11,3,1.0,15:00,15,1800.0,0.0,TB,...,NaN,0.106136,0.893864,0.088340,0.911660,0.893864,0.017796,NaN,NaN,2013
288944,2015-10-25,2015102509,5,1,3.0,04:38,5,2978.0,38.0,SD,...,0.091968,0.214457,0.785543,0.230547,0.769453,0.214457,0.016090,0.014962,0.001128,2015
172450,2012-12-16,2012121604,14,2,2.0,04:59,5,2099.0,39.0,CLE,...,0.256154,0.453662,0.546338,0.435972,0.564028,0.453662,-0.017690,-0.025029,0.007339,2012
95228,2011-09-25,2011092501,13,3,3.0,05:18,6,1218.0,40.0,NO,...,-4.438629,0.428127,0.571873,0.469285,0.530715,0.571873,-0.041157,0.121777,-0.162934,2011
211499,2013-11-28,2013112801,21,4,2.0,04:41,5,281.0,21.0,DAL,...,0.554410,0.994334,0.005666,0.996679,0.003321,0.994334,0.002345,0.001423,0.000921,2013
252456,2014-11-16,2014111607,3,1,3.0,05:16,6,3016.0,43.0,STL,...,-4.296525,0.623829,0.376171,0.564048,0.435952,0.623829,-0.059781,0.086267,-0.146048,2014
380888,2017-10-22,2017102211,23,4,NaN,02:00,2,120.0,8.0,NYG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
11341,2009-10-11,2009101103,4,1,1.0,04:47,5,2987.0,35.0,DET,...,0.047261,0.462242,0.537758,0.488278,0.511722,0.462242,0.026036,0.026663,-0.000627,2009

# See how many missing data points we have
___

Ok, now we know that we do have some missing values. Let's see how many we have in each column.

In [7]:
# get the number of missing data points per column
missing_values_count = nfl_data.isnull().sum()

# look at the # of missing points in the first ten columns
missing_values_count[0:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            61154
time              224
TimeUnder           0
TimeSecs          224
PlayTimeDiff      444
SideofField       528
dtype: int64

That seems like a lot! It might be helpful to see what percentage of the values in our dataset were missing to give us a better sense of the scale of this problem:

In [8]:
# how many total missing values do we have?
total_cells = np.product(nfl_data.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
(total_missing/total_cells) * 100

24.87214126835169

Wow, almost a quarter of the cells in this dataset are empty! In the next step, we're going to take a closer look at some of the columns with missing values and try to figure out what might be going on with them.

In [11]:
# your turn! Find out what percent of the sf_permit dataset is missing
sf_permits_missing_values_count = sf_permits.isnull().sum()
sf_permits_total_cells = np.product(sf_permits.shape)
sf_permits_total_missing = sf_permits_missing_values_count.sum()

# percent of data that is missing
(sf_permits_total_missing/sf_permits_total_cells) * 100

26.26002315058403

# Figure out why the data is missing
____
 
This is the point at which we get into the part of data science that I like to call "data intution", by which I mean "really looking at your data and trying to figure out why it is the way it is and how that will affect your analysis". It can be a frustrating part of data science, especially if you're newer to the field and don't have a lot of experience. For dealing with missing values, you'll need to use your intution to figure out why the value is missing. One of the most important question you can ask yourself to help figure this out is this:

> **Is this value missing becuase it wasn't recorded or becuase it dosen't exist?**

If a value is missing becuase it doens't exist (like the height of the oldest child of someone who doesn't have any children) then it doesn't make sense to try and guess what it might be. These values you probalby do want to keep as NaN. On the other hand, if a value is missing becuase it wasn't recorded, then you can try to guess what it might have been based on the other values in that column and row. (This is called "imputation" and we'll learn how to do it next! :)

Let's work through an example. Looking at the number of missing values in the nfl_data dataframe, I notice that the column `TimesSec` has a lot of missing values in it:

In [13]:
# look at the # of missing points in the first ten columns
missing_values_count[0:10]

Date                0
GameID              0
Drive               0
qtr                 0
down            61154
time              224
TimeUnder           0
TimeSecs          224
PlayTimeDiff      444
SideofField       528
dtype: int64

In [14]:
sf_permits_missing_values_count

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

By looking at [the documentation](https://www.kaggle.com/maxhorowitz/nflplaybyplay2009to2016), I can see that this column has information on the number of seconds left in the game when the play was made. This means that these values are probably missing because they were not recorded, rather than because they don't exist. So, it would make sense for us to try and guess what they should be rather than just leaving them as NA's.

On the other hand, there are other fields, like `PenalizedTeam` that also have lot of missing fields. In this case, though, the field is missing because if there was no penalty then it doesn't make sense to say *which* team was penalized. For this column, it would make more sense to either leave it empty or to add a third value like "neither" and use that to replace the NA's.

> **Tip:** This is a great place to read over the dataset documentation if you haven't already! If you're working with a dataset that you've gotten from another person, you can also try reaching out to them to get more information.

If you're doing very careful data analysis, this is the point at which you'd look at each column individually to figure out the best strategy for filling those missing values. For the rest of this notebook, we'll cover some "quick and dirty" techniques that can help you with missing values but will probably also end up removing some useful information or adding some noise to your data.

## Your turn!

* Look at the columns `Street Number Suffix` and `Zipcode` from the `sf_permits` datasets. Both of these contain missing values. Which, if either, of these are missing because they don't exist? Which, if either, are missing because they weren't recorded?

# Drop missing values
___

If you're in a hurry or don't have a reason to figure out why your values are missing, one option you have is to just remove any rows or columns that contain missing values. (Note: I don't generally recommend this approch for important projects! It's usually worth it to take the time to go through your data and really look at all the columns with missing values one-by-one to really get to know your dataset.)  

If you're sure you want to drop rows with missing values, pandas does have a handy function, `dropna()` to help you do this. Let's try it out on our NFL dataset!

In [15]:
# remove all the rows that contain a missing value
nfl_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

Oh dear, it looks like that's removed all our data! ðŸ˜± This is because every row in our dataset had at least one missing value. We might have better luck removing all the *columns* that have at least one missing value instead.

In [16]:
# remove all columns with at least one missing value
columns_with_na_dropped = nfl_data.dropna(axis=1)
columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,0,None,3,3,3,3,3,0.0,0.0,2009

In [17]:
# just how much data did we lose?
print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

Columns in original dataset: 102

Columns with na's dropped: 41

We've lost quite a bit of data, but at this point we have successfully removed all the `NaN`'s from our data.

In [18]:
# Your turn! Try removing all the rows from the sf_permits dataset that contain missing values. How many are left?
sf_permits_rows_with_na_dropped = sf_permits.dropna()
print("Rows with na's dropped: %d" % sf_permits_rows_with_na_dropped.shape[1])

Rows with na's dropped: 43

In [19]:
# Now try removing all the columns with empty values. Now how much of your data is left?
sf_permits_columns_with_na_dropped = sf_permits.dropna(axis=1)
sf_permits_columns_with_na_dropped.head()
print("Columns with na's dropped: %d" % sf_permits_columns_with_na_dropped.shape[1])

Columns with na's dropped: 12

# Filling in missing values automatically
_____

Another option is to try and fill in the missing values. For this next bit, I'm getting a small sub-section of the NFL data so that it will print well.

In [20]:
# get a small subset of the NFL dataset
subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

We can use the Panda's fillna() function to fill in missing values in a dataframe for us. One option we have is to specify what we want the `NaN` values to be replaced with. Here, I'm saying that I would like to replace all the `NaN` values with 0.

In [21]:
# replace all NA's with 0
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

I could also be a bit more savvy and replace missing values with whatever value comes directly after it in the same column. (This makes a lot of sense for datasets where the observations have some sort of logical order to them.)

In [22]:
# replace all NA's the value that comes directly after it in the same column, 
# then replace all the reamining na's with 0
subset_nfl_data.fillna(method = 'bfill', axis=0).fillna("0")

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.06817,1.14608,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.06817,1.14608,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.31884,-5.03142,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.31884,-5.03142,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0,0,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0,0,2009

Filling in missing values is also known as "imputation", and you can find more exercises on it [in this lesson, also linked under the "More practice!" section](https://www.kaggle.com/dansbecker/handling-missing-values). First, however, why don't you try replacing some of the missing values in the sf_permit dataset?

In [25]:
# Your turn! Try replacing all the NaN's in the sf_permit data with the one that
# comes directly after it and then 
sf_permits.fillna(method = 'bfill', axis=0).fillna("0")

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,A,Ellis,St,...,3,constr type 3,1,constr type 1,Y,3,Tenderloin,94102,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,A,Geary,St,...,3,constr type 3,1,constr type 1,Y,3,Tenderloin,94102,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,A,Pacific,Av,...,1,constr type 1,1,constr type 1,Y,3,Russian Hill,94109,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,A,Pacific,Av,...,5,wood frame (5),5,wood frame (5),Y,3,Nob Hill,94109,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,A,Market,St,...,3,constr type 3,1,constr type 1,Y,6,Tenderloin,94102,"(37.78315261897309, -122.40950883997789)",144548169992
5,201706149344,8,otc alterations permit,06/14/2017,4105,009,800,A,Indiana,St,...,1,constr type 1,1,constr type 1,Y,10,Potrero Hill,94107,"(37.75922331346539, -122.39170402628598)",1466911170855
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,A,11th,Av,...,5,wood frame (5),5,wood frame (5),Y,5,Inner Sunset,94122,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,A,Revere,Av,...,5,wood frame (5),5,wood frame (5),Y,10,Bayview Hunters Point,94124,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,A,Fell,St,...,5,wood frame (5),5,wood frame (5),Y,5,Lone Mountain/USF,94117,"(37.772393498502595, -122.45231466824669)",1469198253772
9,M804767,8,otc alterations permit,07/06/2017,1259,016,89,A,Alpine,Tr,...,5,wood frame (5),5,wood frame (5),Y,8,Haight Ashbury,94117,"(37.7691724293766, -122.43734859051908)",146932394171
10,M805287,8,otc alterations permit,07/06/2017,3541,001,106,A,Sanchez,St,...,5,wood frame (5),5,wood frame (5),Y,8,Castro/Upper Market,94114,"(37.767349757757145, -122.43140682973024)",1469445246849
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,A,Fell,St,...,5,wood frame (5),5,wood frame (5),Y,5,Hayes Valley,94102,"(37.774914087334544, -122.42886839796792)",146961582526
12,M806447,8,otc alterations permit,07/10/2017,6537,023,4082,A,25th,St,...,5,wood frame (5),5,wood frame (5),Y,8,Noe Valley,94114,"(37.75006779619502, -122.43127350268124)",1469781206718
13,201707252846,8,otc alterations permit,07/25/2017,6589,002R,681,A,27th,St,...,5,wood frame (5),5,wood frame (5),Y,8,Noe Valley,94131,"(37.7462205625642, -122.4353484860549)",1471799208305
14,M813729,8,otc alterations permit,07/26/2017,1049,027,2761,A,Pine,St,...,5,wood frame (5),5,wood frame (5),Y,2,Pacific Heights,94115,"(37.78676200041077, -122.44124093333335)",147203988249
15,M813907,8,otc alterations permit,07/27/2017,0243,043,840,A,Powell,St,...,5,wood frame (5),5,wood frame (5),Y,3,Chinatown,94108,"(37.7926690651263, -122.40883941791454)",147208763456
16,M813967,8,otc alterations permit,07/27/2017,0268,008,220,A,Montgomery,St,...,5,wood frame (5),5,wood frame (5),Y,3,Financial District/South Beach,94104,"(37.79130641988351, -122.40198579459195)",147211866168
17,M814148,8,otc alterations permit,07/27/2017,3621,097,3707,A,21st,St,...,5,wood frame (5),5,wood frame (5),Y,8,Noe Valley,94114,"(37.75607840165479, -122.43041143390109)",1472184412108
18,201707283165,8,otc alterations permit,07/28/2017,0472,042,1307,A,Bay,St,...,5,wood frame (5),5,wood frame (5),Y,2,Marina,94123,"(37.8035183252307, -122.42863180996076)",1472277302360
19,M814368,8,otc alterations permit,07/28/2017,2659,001,263,A,Corbett,Av,...,5,wood frame (5),5,wood frame (5),Y,8,Castro/Upper Market,94114,"(37.761092365437214, -122.44402154957145)",1472295408612
20,M814967,8,otc alterations permit,07/31/2017,1176,068,1624,A,Fulton,St,...,5,wood frame (5),5,wood frame (5),Y,5,Lone Mountain/USF,94117,"(37.77640228859421, -122.44361679686382)",1472619503582
21,201708013476,8,otc alterations permit,08/01/2017,6529,010,3410,A,26th,St,...,5,wood frame (5),5,wood frame (5),Y,9,Mission,94110,"(37.74914175355125, -122.41849211166853)",1472727381751
22,201708013544,3,additions alterations or repairs,08/01/2017,0074,043,2150,A,Taylor,St,...,5,wood frame (5),5,wood frame (5),Y,3,Russian Hill,94133,"(37.802405951667645, -122.41446286561653)",147281357792
23,M816927,8,otc alterations permit,08/07/2017,0941,012,2824,A,Filbert,St,...,5,wood frame (5),5,wood frame (5),Y,2,Marina,94123,"(37.79697456740493, -122.44615769723546)",147359384812
24,201708084249,8,otc alterations permit,08/08/2017,0542,039,1,A,Charlton,Ct,...,5,wood frame (5),5,wood frame (5),Y,2,Marina,94123,"(37.79739093461306, -122.43127133823367)",1473796372030
25,201708165014,8,otc alterations permit,08/16/2017,1824,006,1435,A,29th,Av,...,5,wood frame (5),5,wood frame (5),Y,4,Sunset/Parkside,94122,"(37.76052279949518, -122.4879889739165)",1474841115935
26,M820728,8,otc alterations permit,08/18/2017,1449,006,331,A,17th,Av,...,5,wood frame (5),5,wood frame (5),Y,1,Outer Richmond,94121,"(37.78177022745135, -122.47658979438802)",1475223100163
27,M821207,8,otc alterations permit,08/21/2017,1193,024,120,A,Shrader,St,...,5,wood frame (5),5,wood frame (5),Y,5,Lone Mountain/USF,94117,"(37.77371007080848, -122.45243180846707)",147537591942
28,M821268,8,otc alterations permit,08/21/2017,1851,012,1512,A,06th,Av,...,5,wood frame (5),5,wood frame (5),Y,7,Inner Sunset,94122,"(37.760252335082875, -122.4625393396095)",1475405117215
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,A,Powell,St,...,5,wood frame (5),5,wood frame (5),Y,3,Tenderloin,94102,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,M893328,8,otc alterations permit,02/23/2018,0025,024,888,0,North Point,St,...,5,wood frame (5),5,wood frame (5),0,2,Russian Hill,94109,"(37.8057495627139, -122.42181538597318)",1498327347381
198871,M893347,8,otc alterations permit,02/23/2018,1253,001,701,0,Clayton,St,...,5,wood frame (5),5,wood frame (5),0,5,Haight Ashbury,94117,"(37.76869660680249, -122.44864582118123)",1498328241068
198872,201802232165,8,otc alterations permit,02/23/2018,3543,012,2123,0,Market,St,...,5,wood frame (5),5,wood frame (5),0,8,Castro/Upper Market,94114,"(37.76682151637876, -122.42926240167795)",1498329423799
198873,201802232166,8,otc alterations permit,02/23/2018,5723,041,100,0,Tompkins,Av,...,5,wood frame (5),5,wood frame (5),0,9,Bernal Heights,94110,"(37.73708421334594, -122.4157759256698)",1498330475722
198874,201802232106,8,otc alterations permit,02/23/2018,6592,023,336,0,Duncan,St,...,5,wood frame (5),5,wood frame (5),0,8,Noe Valley,94131,"(37.746231746880696, -122.4285179313817)",1498331399024
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,0,Hayes,St,...,5,wood frame (5),1,constr type 1,0,5,Hayes Valley,94102,"(37.776756688343944, -122.4260292019233)",149833282001
198876,M893367,8,otc alterations permit,02/23/2018,1213,013,500,0,Stanyan,St,...,5,wood frame (5),5,wood frame (5),0,5,Lone Mountain/USF,94117,"(37.77277103274044, -122.45392960440346)",149833392632
198877,201802232169,8,otc alterations permit,02/23/2018,7103,020,91,0,Lobos,St,...,5,wood frame (5),5,wood frame (5),0,11,Oceanview/Merced/Ingleside,94112,"(37.7146765393289, -122.45557353560899)",1498334221586
198878,201802232170,8,otc alterations permit,02/23/2018,3641,016,3134,0,24th,St,...,5,wood frame (5),5,wood frame (5),0,9,Mission,94110,"(37.752661001157854, -122.41485533400166)",1498335409431
198879,201802232171,8,otc alterations permit,02/23/2018,6082,009,350,0,Paris,St,...,5,wood frame (5),5,wood frame (5),0,11,Excelsior,94112,"(37.72324934238285, -122.43409219261636)",1498336195616
198880,M893387,8,otc alterations permit,02/23/2018,1841,025D,1442,0,Funston,Av,...,5,wood frame (5),5,wood frame (5),0,7,Inner Sunset,94122,"(37.76117190796411, -122.47007880106999)",1498337116842
198881,M893407,8,otc alterations permit,02/23/2018,0018,004,2300,0,Stockton,St,...,5,wood frame (5),5,wood frame (5),0,3,North Beach,94133,"(37.80747140583783, -122.41024025753224)",1498338347099
198882,201802232172,8,otc alterations permit,02/23/2018,6021,001B,730,0,Excelsior,Av,...,5,wood frame (5),5,wood frame (5),0,11,Excelsior,94112,"(37.723206757170836, -122.42763728105176)",1498339194341
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,0,Geary,St,...,5,wood frame (5),5,wood frame (5),0,3,Tenderloin,94102,"(37.78696971667916, -122.40936701144197)",149834069380
198884,M893447,8,otc alterations permit,02/23/2018,3504,030,1699,0,Market,St,...,5,wood frame (5),5,wood frame (5),0,6,Mission,94103,"(37.77217130976155, -122.42193576313322)",1498341156230
198885,201802232173,8,otc alterations permit,02/23/2018,2150,001A,2007,0,30th,Av,...,5,wood frame (5),5,wood frame (5),0,4,Sunset/Parkside,94116,"(37.74976582284573, -122.48824447038214)",1498342127659
198886,201709066971,3,additions alterations or repairs,09/06/2017,0999,025,3191,0,Washington,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1477559238559
198887,201710040362,8,otc alterations permit,10/04/2017,0750,001,1521,0,Eddy,St,...,1,constr type 1,1,constr type 1,0,0,0,0,0,1482126434174
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,0,Steiner,St,...,1,constr type 1,1,constr type 1,0,0,0,0,0,1483035367814
198889,201710242114,8,otc alterations permit,10/24/2017,1654,035,748,0,12th,Av,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1484587273155
198890,201711274822,3,additions alterations or repairs,11/27/2017,3803,001,185,0,Berry,St,...,1,constr type 1,1,constr type 1,0,0,0,0,0,1488352388160
198891,201711274844,8,otc alterations permit,11/27/2017,0766,008,590,0,Van Ness,Av,...,3,constr type 3,3,constr type 3,0,0,0,0,0,148838081446
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,0,Mcallister,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,0,Clay,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1489281258414
198894,201712055493,8,otc alterations permit,12/05/2017,3522,006,340,0,12th,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1489308256860
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,0,Montgomery,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,0,Bush,St,...,5,wood frame (5),5,wood frame (5),0,0,0,0,0,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,0,Indiana,St,...,0,0,0,0,0,0,0,0,0,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,0,Sutter,St,...,0,0,0,0,0,0,0,0,0,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,0,Pacific,Av,...,0,0,0,0,0,0,0,0,0,1489796283803

And that's it for today! If you have any questions, be sure to post them in the comments below or [on the forums](https://www.kaggle.com/questions-and-answers). 

Remember that your notebook is private by default, and in order to share it with other people or ask for help with it, you'll need to make it public. First, you'll need to save a version of your notebook that shows your current work by hitting the "Commit & Run" button. (Your work is saved automatically, but versioning your work lets you go back and look at what it was like at the point you saved it. It also let's you share a nice compiled notebook instead of just the raw code.) Then, once your notebook is finished running, you can go to the Settings tab in the panel to the left (you may have to expand it by hitting the [<] button next to the "Commit & Run" button) and setting the "Visibility" dropdown to "Public".

# More practice!
___

If you're looking for more practice handling missing values, check out these extra-credit\* exercises:

* [Handling Missing Values](https://www.kaggle.com/dansbecker/handling-missing-values): In this notebook Dan shows you several approaches to imputing missing data using scikit-learn's imputer. 
* Look back at the `Zipcode` column in the `sf_permits` dataset, which has some missing values. How would you go about figuring out what the actual zipcode of each address should be? (You might try using another dataset, like the [OpenAddresses dataset](https://www.kaggle.com/openaddresses/openaddresses-us-west).) 

\* no actual credit is given for completing the challenge, you just learn how to clean data real good :P